# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/vincenzo/clion-2018.3.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/vincenzo/clion-2018.3.3/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vincenzo/Github/SpyCBlockRPC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vincenzo/Github/SpyCBlockRPC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/vincenzo/clion-2018.3.3/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/vincenzo/clion-2018.3.3/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vincenzo/Github/SpyCBlockRPC/CMakeFiles /home/vincenzo/Github/SpyCBlockRPC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vincenzo/Github/SpyCBlockRPC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SpyCBlockRPC

# Build rule for target.
SpyCBlockRPC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpyCBlockRPC
.PHONY : SpyCBlockRPC

# fast build rule for target.
SpyCBlockRPC/fast:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/build
.PHONY : SpyCBlockRPC/fast

lib/cpp-properties/src/Properties.o: lib/cpp-properties/src/Properties.cpp.o

.PHONY : lib/cpp-properties/src/Properties.o

# target to build an object file
lib/cpp-properties/src/Properties.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/lib/cpp-properties/src/Properties.cpp.o
.PHONY : lib/cpp-properties/src/Properties.cpp.o

lib/cpp-properties/src/Properties.i: lib/cpp-properties/src/Properties.cpp.i

.PHONY : lib/cpp-properties/src/Properties.i

# target to preprocess a source file
lib/cpp-properties/src/Properties.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/lib/cpp-properties/src/Properties.cpp.i
.PHONY : lib/cpp-properties/src/Properties.cpp.i

lib/cpp-properties/src/Properties.s: lib/cpp-properties/src/Properties.cpp.s

.PHONY : lib/cpp-properties/src/Properties.s

# target to generate assembly for a file
lib/cpp-properties/src/Properties.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/lib/cpp-properties/src/Properties.cpp.s
.PHONY : lib/cpp-properties/src/Properties.cpp.s

lib/cpp-properties/src/PropertiesParser.o: lib/cpp-properties/src/PropertiesParser.cpp.o

.PHONY : lib/cpp-properties/src/PropertiesParser.o

# target to build an object file
lib/cpp-properties/src/PropertiesParser.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/lib/cpp-properties/src/PropertiesParser.cpp.o
.PHONY : lib/cpp-properties/src/PropertiesParser.cpp.o

lib/cpp-properties/src/PropertiesParser.i: lib/cpp-properties/src/PropertiesParser.cpp.i

.PHONY : lib/cpp-properties/src/PropertiesParser.i

# target to preprocess a source file
lib/cpp-properties/src/PropertiesParser.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/lib/cpp-properties/src/PropertiesParser.cpp.i
.PHONY : lib/cpp-properties/src/PropertiesParser.cpp.i

lib/cpp-properties/src/PropertiesParser.s: lib/cpp-properties/src/PropertiesParser.cpp.s

.PHONY : lib/cpp-properties/src/PropertiesParser.s

# target to generate assembly for a file
lib/cpp-properties/src/PropertiesParser.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/lib/cpp-properties/src/PropertiesParser.cpp.s
.PHONY : lib/cpp-properties/src/PropertiesParser.cpp.s

lib/cpp-properties/src/PropertiesUtils.o: lib/cpp-properties/src/PropertiesUtils.cpp.o

.PHONY : lib/cpp-properties/src/PropertiesUtils.o

# target to build an object file
lib/cpp-properties/src/PropertiesUtils.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/lib/cpp-properties/src/PropertiesUtils.cpp.o
.PHONY : lib/cpp-properties/src/PropertiesUtils.cpp.o

lib/cpp-properties/src/PropertiesUtils.i: lib/cpp-properties/src/PropertiesUtils.cpp.i

.PHONY : lib/cpp-properties/src/PropertiesUtils.i

# target to preprocess a source file
lib/cpp-properties/src/PropertiesUtils.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/lib/cpp-properties/src/PropertiesUtils.cpp.i
.PHONY : lib/cpp-properties/src/PropertiesUtils.cpp.i

lib/cpp-properties/src/PropertiesUtils.s: lib/cpp-properties/src/PropertiesUtils.cpp.s

.PHONY : lib/cpp-properties/src/PropertiesUtils.s

# target to generate assembly for a file
lib/cpp-properties/src/PropertiesUtils.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/lib/cpp-properties/src/PropertiesUtils.cpp.s
.PHONY : lib/cpp-properties/src/PropertiesUtils.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SpyCBlockRPC.dir/build.make CMakeFiles/SpyCBlockRPC.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... SpyCBlockRPC"
	@echo "... edit_cache"
	@echo "... lib/cpp-properties/src/Properties.o"
	@echo "... lib/cpp-properties/src/Properties.i"
	@echo "... lib/cpp-properties/src/Properties.s"
	@echo "... lib/cpp-properties/src/PropertiesParser.o"
	@echo "... lib/cpp-properties/src/PropertiesParser.i"
	@echo "... lib/cpp-properties/src/PropertiesParser.s"
	@echo "... lib/cpp-properties/src/PropertiesUtils.o"
	@echo "... lib/cpp-properties/src/PropertiesUtils.i"
	@echo "... lib/cpp-properties/src/PropertiesUtils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

